// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using thrucommunity.Data;

#nullable disable

namespace thrucommunity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701200505_Profiles")]
    partial class Profiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("thrucommunity.Models.PlayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstPlaceCount")
                        .HasColumnType("integer");

                    b.Property<int>("L1CCcount")
                        .HasColumnType("integer");

                    b.Property<int>("LNBNxcount")
                        .HasColumnType("integer");

                    b.Property<int>("LNBcount")
                        .HasColumnType("integer");

                    b.Property<int>("LNMcount")
                        .HasColumnType("integer");

                    b.Property<int>("LNNNcount")
                        .HasColumnType("integer");

                    b.Property<int>("LNNcount")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SecondPlaceCount")
                        .HasColumnType("integer");

                    b.Property<int>("ThirdPlaceCount")
                        .HasColumnType("integer");

                    b.Property<int>("WRcount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("thrucommunity.Models.ReplayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DeathCount")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NoBomb")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoMiss")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoThirdCondition")
                        .HasColumnType("boolean");

                    b.Property<bool>("Proven")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReplayDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplayFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplayFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplayLink")
                        .HasColumnType("text");

                    b.Property<long?>("Score")
                        .HasColumnType("bigint");

                    b.Property<string>("ShotType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubmissionStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeOfSurvival")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Replays");
                });
#pragma warning restore 612, 618
        }
    }
}
